---
title: "Takım: R We Ready"
sidebar: false 
---

MUY665-İş Analitiği dersi takım sayfamıza hoş geldiniz.

Bu analitik çalışmalarımızı paylaşıyoruz.

Lütfen faaliyetlerimizi görmek için için bizi takipte kalın.

## Takım Üyeleri

1.  [Gökay Tamzaralıoğlu](/takim/gokaytamzaralioglu.qmd "Gökay Tamzaralıoğlu")

2.  [Hilalnur Beral Tamzaralıoğlu](/takim/hilalberal.qmd "Hilalnur Beral Tamzaralıoğlu")

3.  [Serkan Ünlü](/takim/fred.qmd "Serkan Ünlü")

4.  [Ahmet Hikmet Aydoğan](/takim/szymanski.qmd "Ahmet Hikmet Aydoğan")

5.  [Efrumiye Aktaş](/takim/efrumiye.qmd "Efrumiye Aktaş")

## Proje Adı

MUY665-İş Analitiği iyileştirme çalışmaları (örnek)

## Proje Konusu

Örnek: Bu projede MUY660-İş Analitiği ders içeriğinin analitik yaklaşımlarla iyileştirilmesini hedefledik. Bu doğrultuda tüm üniversitelerdeki benzer derslerin verisini toplayarak bir veri seti oluşturduk Analiz için ........ yöntemleri kullanarak, ....... çalışmaları yaptık Sonuç olarak, MUY660-İş Analitiği dersinin dünyadaki tüm derslerden daha iyi olduğunu ve bu dersi aldığımız için çok mutlu olduğumuzu tespit ettik.

## Veri Seti Hakkında Özet Bilgi

## Sonuçlar

Burada key takeways verilmelidir. En az 3 en fazla 5 madde ile çarpıcı sonuçlar sunulmalıdır.
